# Generated by Django 3.2.1 on 2021-05-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virdet_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nKits', models.IntegerField()),
                ('encrypted_data', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='virdet_website.token')),
            ],
        ),
    ]
